/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenID Connect Discovery
         * @description Returns OIDC configuration metadata (RFC 8414)
         */
        get: operations["getDiscoveryDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JSON Web Key Set (JWKS)
         * @description Returns public keys for JWT signature verification (RFC 7517)
         */
        get: operations["getJWKS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorization Endpoint
         * @description Initiates OAuth 2.0 Authorization Code Flow with PKCE.
         *     Redirects to login page if user not authenticated.
         */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token Endpoint
         * @description Exchanges authorization code for tokens or refreshes access token.
         *
         *     **Grant Types**:
         *     - authorization_code: Exchange code for tokens
         *     - refresh_token: Get new access token
         *
         *     **Rate Limit**: 10 requests/minute per client_id
         */
        post: operations["token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token Revocation
         * @description Revokes a refresh token (RFC 7009).
         *     Returns 200 OK even if token doesn't exist (security best practice).
         */
        post: operations["revokeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * UserInfo Endpoint
         * @description Returns user profile information (OIDC UserInfo endpoint)
         */
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clients
         * @description Lists all client applications for the authenticated tenant
         */
        get: operations["listClients"];
        put?: never;
        /**
         * Create Client
         * @description Registers a new client application for the tenant
         */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client
         * @description Retrieves details of a specific client
         */
        get: operations["getClient"];
        /**
         * Update Client
         * @description Updates client application settings
         */
        put: operations["updateClient"];
        post?: never;
        /**
         * Delete Client
         * @description Deletes a client application (revokes all tokens)
         */
        delete: operations["deleteClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clients/{client_id}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Client Secret
         * @description Generates a new client secret (invalidates old one)
         */
        post: operations["regenerateClientSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Role Assignments
         * @description Lists all user role assignments for the tenant
         */
        get: operations["listRoleAssignments"];
        put?: never;
        /**
         * Assign Role
         * @description Grants a user access to a client application with a specific role
         */
        post: operations["assignRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Role
         * @description Revokes a user's access to a client application
         */
        delete: operations["revokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OIDCDiscovery: {
            issuer?: string;
            authorization_endpoint?: string;
            token_endpoint?: string;
            jwks_uri?: string;
            userinfo_endpoint?: string;
            revocation_endpoint?: string;
            scopes_supported?: string[];
            response_types_supported?: string[];
            grant_types_supported?: string[];
            code_challenge_methods_supported?: string[];
            token_endpoint_auth_methods_supported?: string[];
        };
        JWKS: {
            keys?: {
                kty?: string;
                use?: string;
                kid?: string;
                alg?: string;
                n?: string;
                e?: string;
            }[];
        };
        AuthorizationCodeGrant: {
            /** @enum {string} */
            grant_type: "authorization_code";
            code: string;
            redirect_uri: string;
            code_verifier: string;
            client_id: string;
            client_secret: string;
        };
        RefreshTokenGrant: {
            /** @enum {string} */
            grant_type: "refresh_token";
            refresh_token: string;
            client_id: string;
            client_secret: string;
        };
        TokenResponse: {
            access_token?: string;
            /** @enum {string} */
            token_type?: "Bearer";
            /** @description Access token lifetime in seconds */
            expires_in?: number;
            /** @description OIDC ID token (only for authorization_code grant) */
            id_token?: string;
            refresh_token?: string;
            scope?: string;
        };
        UserInfo: {
            /** @description User identifier */
            sub?: string;
            email?: string;
            email_verified?: boolean;
            name?: string;
            given_name?: string;
            family_name?: string;
            tenant_id?: string;
        };
        Client: {
            client_id?: string;
            client_name?: string;
            redirect_uris?: string[];
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ClientCredentials: components["schemas"]["Client"] & {
            /** @description Only returned on creation */
            client_secret?: string;
        };
        CreateClientRequest: {
            client_name: string;
            redirect_uris: string[];
        };
        UpdateClientRequest: {
            client_name?: string;
            redirect_uris?: string[];
            is_active?: boolean;
        };
        RoleAssignment: {
            id?: number;
            user_id?: string;
            client_id?: string;
            role?: string;
            is_active?: boolean;
            /** Format: date-time */
            granted_at?: string;
            granted_by?: string;
        };
        AssignRoleRequest: {
            user_id: string;
            client_id: string;
            /** @enum {string} */
            role: "admin" | "user" | "viewer";
        };
        OAuth2Error: {
            /** @enum {string} */
            error?: "invalid_request" | "invalid_client" | "invalid_grant" | "unauthorized_client" | "unsupported_grant_type" | "invalid_scope" | "too_many_requests";
            error_description?: string;
            error_uri?: string;
        };
        Error: {
            error?: string;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDiscoveryDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC discovery document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "issuer": "https://sso.keyles.com",
                     *       "authorization_endpoint": "https://sso.keyles.com/oauth2/auth",
                     *       "token_endpoint": "https://sso.keyles.com/oauth2/token",
                     *       "jwks_uri": "https://sso.keyles.com/.well-known/jwks.json",
                     *       "userinfo_endpoint": "https://sso.keyles.com/oauth2/userinfo",
                     *       "revocation_endpoint": "https://sso.keyles.com/oauth2/revoke",
                     *       "scopes_supported": [
                     *         "openid",
                     *         "profile",
                     *         "email"
                     *       ],
                     *       "response_types_supported": [
                     *         "code"
                     *       ],
                     *       "grant_types_supported": [
                     *         "authorization_code",
                     *         "refresh_token"
                     *       ],
                     *       "code_challenge_methods_supported": [
                     *         "S256"
                     *       ],
                     *       "token_endpoint_auth_methods_supported": [
                     *         "client_secret_post"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["OIDCDiscovery"];
                };
            };
        };
    };
    getJWKS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JWKS document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "keys": [
                     *         {
                     *           "kty": "RSA",
                     *           "use": "sig",
                     *           "kid": "key_2025_01",
                     *           "alg": "RS256",
                     *           "n": "modulus_base64url",
                     *           "e": "AQAB"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["JWKS"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                /**
                 * @description Client identifier
                 * @example abc123xyz
                 */
                client_id: string;
                /**
                 * @description Callback URI (must match registered URI)
                 * @example https://client-app.example.com/callback
                 */
                redirect_uri: string;
                /** @description Must be "code" */
                response_type: "code";
                /**
                 * @description Space-separated scopes (must include "openid")
                 * @example openid profile email
                 */
                scope: string;
                /**
                 * @description CSRF protection token
                 * @example random-csrf-token-12345
                 */
                state: string;
                /**
                 * @description PKCE code challenge (BASE64URL(SHA256(code_verifier)))
                 * @example E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
                 */
                code_challenge: string;
                /** @description Must be "S256" */
                code_challenge_method: "S256";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to login page or back to client with authorization code */
            302: {
                headers: {
                    /** @description Redirect URL */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2Error"];
                };
            };
        };
    };
    token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AuthorizationCodeGrant"] | components["schemas"]["RefreshTokenGrant"];
            };
        };
        responses: {
            /** @description Tokens issued successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleV8yMDI1XzAxIn0...",
                     *       "token_type": "Bearer",
                     *       "expires_in": 900,
                     *       "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleV8yMDI1XzAxIn0...",
                     *       "refresh_token": "refresh_9z8y7x6w5v4u3t2s1r0q",
                     *       "scope": "openid profile email"
                     *     }
                     */
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid grant */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid_grant",
                     *       "error_description": "The authorization code is invalid, expired, or has already been used"
                     *     }
                     */
                    "application/json": components["schemas"]["OAuth2Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    /** @example 10 */
                    "X-RateLimit-Limit"?: number;
                    /** @example 0 */
                    "X-RateLimit-Remaining"?: number;
                    /** @example 60 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "too_many_requests",
                     *       "error_description": "Rate limit exceeded. Try again in 60 seconds."
                     *     }
                     */
                    "application/json": components["schemas"]["OAuth2Error"];
                };
            };
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Token to revoke */
                    token: string;
                    /**
                     * @description Type of token (optional)
                     * @enum {string}
                     */
                    token_type_hint?: "refresh_token";
                    /** @description Client identifier */
                    client_id: string;
                    /** @description Client secret */
                    client_secret: string;
                };
            };
        };
        responses: {
            /** @description Token revoked successfully (or didn't exist) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example revoked */
                        status?: string;
                    };
                };
            };
            /** @description Invalid client credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2Error"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "sub": "user_12345",
                     *       "email": "user@tenant-a.com",
                     *       "email_verified": true,
                     *       "name": "John Doe",
                     *       "given_name": "John",
                     *       "family_name": "Doe",
                     *       "tenant_id": "tenant_a"
                     *     }
                     */
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Invalid or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2Error"];
                };
            };
        };
    };
    listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "clients": [
                     *         {
                     *           "client_id": "abc123xyz",
                     *           "client_name": "Mobile App",
                     *           "redirect_uris": [
                     *             "https://app.example.com/callback"
                     *           ],
                     *           "is_active": true,
                     *           "created_at": "2025-12-26T10:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        clients?: components["schemas"]["Client"][];
                    };
                };
            };
            /** @description Unauthorized - session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "client_name": "Mobile App",
                 *       "redirect_uris": [
                 *         "https://app.example.com/callback",
                 *         "https://app.example.com/auth/callback"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreateClientRequest"];
            };
        };
        responses: {
            /** @description Client created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "client_id": "abc123xyz",
                     *       "client_secret": "secret_98765zyxwvut",
                     *       "client_name": "Mobile App",
                     *       "redirect_uris": [
                     *         "https://app.example.com/callback"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ClientCredentials"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientRequest"];
            };
        };
        responses: {
            /** @description Client updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regenerateClientSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New client secret generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_secret?: string;
                    };
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRoleAssignments: {
        parameters: {
            query?: {
                /** @description Filter by client */
                client_id?: string;
                /** @description Filter by user */
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of role assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        role_assignments?: components["schemas"]["RoleAssignment"][];
                    };
                };
            };
        };
    };
    assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "user_id": "user_12345",
                 *       "client_id": "abc123xyz",
                 *       "role": "user"
                 *     }
                 */
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description Role assigned successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role revoked successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}

/**
 * Tenant status enum - represents the lifecycle status of a tenant
 */
export type TenantStatus = 'pending_verification' | 'active' | 'suspended' | 'deleted';

/**
 * API Exception class for handling API errors
 */
export class ApiException extends Error {
  constructor(
    public status: number,
    public message: string,
    public code?: string
  ) {
    super(message);
    this.name = 'ApiException';
  }
}
